### PR TITLE
remove Jay Carey and add Chris Norman as new maintainer

### PR DESCRIPTION
**Pull request by lbergelson**
Jay Carey has expressed interest in retiring as project maintainer. I would like to nominate @cmnbroad as a replacement maintainer.

### CODE REVIEW

**Review by tfenne — APPROVED** [review]

**Comment by tfenne** [comment]
@magicDGS & @jacarey any objections?

**Comment by lbergelson** [comment]
@cmnbroad Did we spell your various names right?

**Review by magicDGS — APPROVED** [review]
Sure!

**Comment by cmnbroad** [comment]
:+1:

**Review by jacarey — APPROVED** [review]

**Pull request merged**
