### PR TITLE
Add badges to README and AppVeyor configuration

### PR DESCRIPTION
**Pull request by magicDGS**
- Add build badges (Travis-CI and AppVeyor)
- Add LICENSE and language badges
- Add configuration for AppVeyor to test in Windows systems

### CODE REVIEW

**Comment by magicDGS** [comment]
Please, @samtools/htsjdk-next-maintainers - let me know if you would like to receive notifications from AppVeyor to your email for build status

**Comment by magicDGS** [comment]
By the way, for AppVeyor we can create an administrator account to grant access to all the team - but I am not sure how should we sign in (I did it with my own account, but I am not sure if this will be the proper/desired way).

**Comment by lbergelson** [comment]
I signed in to appveyor but it doesn't seem like I have permissions to do anything with the project.  Is there any way to have it respect github permissions like travis does?  I.e. if you're a committer on the project you're a automatically given permissions to administer it in appveyor?  That would be best so there isn't a possibility of it getting out of sync with the list of maintainers.

**Comment by magicDGS** [comment]
That's the wierd thing in AppVeyor: you can add a team, but it gives permissions to the account if set to administrators; it means that it grant access to all the projects. I can also add as users, but then if I grant access to "users" to another repo, the maintainers of htsjdk will also get it.

Maybe we should create an account for the project and then grant access to all the maintainers as administrators; or much better, an account for the github organization and like that all projects can setup AppVeyor and grant access. Whatever you prefer...

**Pull request merged**
